name: Deploy to Azure Static Web App

on:
  push:
    branches:
      - main  # শুধু main ব্রাঞ্চে push করলে চলবে

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Deploy to Azure Static Web Apps
        uses: Azure/static-web-apps-deploy@v1
        with:
          AZURE_STATIC_WEB_APPS_API_TOKEN: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_27_MARCH }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}  # Authentication জন্য
          action: "upload"
          app_location: "/"    # তোমার Static Web App-এর মূল ফোল্ডার
          output_location: "/" # Build ফোল্ডার (যদি থাকে)
